name: Testing Action
on: push
jobs:
  commit:
    name: commit
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: arbitrarily make changes
        id: changes
        if: contains(github.event.head_commit.message, 'yes')
        run: echo test > testing
      - name: commit if necessary
        id: commit
        run: >-
          if [[ ! `git diff-index --quiet HEAD --` ]]; then
            git config user.email action@github.com &&
            git config user.name 'Github Action' &&
            git commit -m 'some commit' testing &&
            echo ::set-output name=push::true
      - name: run if there were changes to commit
        run: echo ${{steps.commit.outputs.push}}
