name: Testing Action
on: [pull_request, push]
jobs:
  refs:
    name: refs
    runs-on: ubuntu-latest
    steps:
      - name: ref
        run: echo ${{github.ref}}
      - name: head_ref
        run: echo ${{github.head_ref}}
        if: github.event_name == 'pull_request'
      - name: base_ref
        run: echo ${{github.base_ref}}
        if: github.event_name == 'pull_request'
