name: Testing Action
on:
  pull_request:
  push:
  check_suite:
    types: [completed]
jobs:
  context:
    name: context
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: github
        run: echo '${{toJson(github)}}'
      - name: github.event
        run: echo '${{toJson(github.event)}}'
